FROM ubuntu

EXPOSE 1337

RUN apt-get update
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN apt-get install -y vim
RUN python3 -m pip install pymongo openpyxl web.py bs4
RUN apt-get install -y mongodb
RUN mkdir ClimatePrisms
COPY . ClimatePrisms

CMD bash ClimatePrisms/docker-embedded.sh

